apiVersion: v1
kind: Pod
metadata:
  name: simple
spec: ##we tell k8s api manager what has to be done
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
        ## first 4 lines are just information 
